"""Generate walkthrough.ipynb for the MATCHA (Paper2Code) repository."""
import json

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src.split("\n")}

def code(src):
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": src.split("\n")}

cells = []

# 1. Title / overview
cells.append(md(
"""# MATCHA — Multi-Agent Conversational Game Recommendation (Walkthrough)

This notebook walks through the code repository generated by **Paper2Code** from the paper:

> *Toward Safe and Human-Aligned Game Conversational Recommendation via Multi-Agent Decomposition* (arXiv:2504.20094)

MATCHA is a **training-free, multi-agent framework** for conversational recommender systems (CRS) in games. It decomposes a recommendation into a pipeline of specialised agents:

```
Intent Agent → Tool-augmented Candidate Generation → Multi-LLM Ranking (+ Reflection) → Explanation
                        ↑
                  Risk Control (RA-LLM + CoT jailbreak detection)  [wraps input & output]
```

What this notebook shows:
1. Loading the project configuration (`config.yaml`).
2. Building the in-memory game database.
3. Instantiating the `MatchaPipeline`.
4. Running a single `recommend()` call end-to-end.
5. Running the full benchmark / ablations via `main.py`.
"""
))

# 2. Repo structure
cells.append(md(
"""## Repository structure

```
MATCHA_repo/
├── config.yaml            # all paper hyperparameters ([paper] vs [assumed] tagged)
├── requirements.txt       # pinned dependencies
├── schemas.py             # Pydantic data models (Request, RecOutput, scores, ...)
├── llm_client.py          # async multi-provider LLM client (OpenAI/Gemini/compatible) + cache
├── prompts.py             # all agent prompt templates
├── dataset_loader.py      # OMuleT / WildJailbreak / DAN / ReDial loaders
├── game_database.py       # in-memory catalog + SBERT/BM25/popularity indexes
├── tools.py               # tool implementations for candidate generation
├── agents/
│   ├── intent_agent.py    # intent parsing (genres, devices, age, mechanics)
│   ├── candidate_agent.py # tool-augmented candidate retrieval (cap 30)
│   ├── ranking_agent.py   # multi-LLM scoring over 5 dimensions
│   ├── reflection_agent.py# reflect on top-8 candidates
│   ├── explanation_agent.py
│   └── risk_control.py    # RA-LLM + CoT jailbreak / dangerous-content control
├── matcha_pipeline.py     # MatchaPipeline — orchestrates the agents
├── baselines.py           # Pop / Base-LLM / MACRS-C baselines
├── judge.py               # virtual judge (Explanation Score 0-5)
├── evaluation.py          # Hit@5, Pop50, Factual, JP, Explanation Score, ...
└── main.py                # CLI entry point (main / jailbreak / ablation / judge)
```
"""
))

# 3. Prerequisites
cells.append(md(
"""## 0. Prerequisites

Install dependencies and provide data + LLM keys:

```bash
pip install -r requirements.txt
```

- **Data**: place the OMuleT files at the paths in `config.yaml`
  (`data.omulet_requests_path`, `data.catalog_path`). WildJailbreak/DAN/ReDial are
  loaded lazily from HuggingFace and are only needed for the jailbreak / cross-domain
  experiments.
- **LLM keys**: the paper uses GPT-4o + Gemini for ranking and LLaMA (vLLM) as baseline
  backbones. Export `OPENAI_API_KEY` and `GOOGLE_API_KEY`. Set
  `matcha.backbone` / `matcha.ranking.llm_a|llm_b` in `config.yaml` accordingly.
"""
))

# 4. Imports + load config
cells.append(code(
"""import json, sys
from pathlib import Path
import pandas as pd

REPO = Path.cwd()  # run this notebook from inside MATCHA_repo/

from main import load_config
from game_database import GameDatabase
from matcha_pipeline import MatchaPipeline

cfg = load_config("config.yaml")
print("Loaded config sections:", sorted(cfg.keys()))
print("MATCHA backbone:", cfg["matcha"]["backbone"])
"""
))

# 5. Build a synthetic catalog + GameDatabase
cells.append(code(
"""# A minimal synthetic catalog so the notebook runs without the real OMuleT files.
# Replace this with `DatasetLoader(cfg).load_catalog()` for the real benchmark.
synthetic_catalog = pd.DataFrame([
    {"game_id": "g1", "name": "Adopt Me!",            "genre": "Simulation", "upvotes": 5200,
     "description": "Raise pets and decorate homes in a social sandbox.", "devices": ["PC", "Mobile"], "tags": ["casual", "social"]},
    {"game_id": "g2", "name": "Blox Fruits",          "genre": "Adventure", "upvotes": 4100,
     "description": "Explore islands, fight bosses and collect devil fruits.", "devices": ["PC"], "tags": ["anime", "grinding"]},
    {"game_id": "g3", "name": "Murder Mystery 2",     "genre": "Horror",    "upvotes": 3300,
     "description": "Social deduction: find the murderer before you are next.", "devices": ["PC", "Mobile"], "tags": ["social", "mystery"]},
    {"game_id": "g4", "name": "Tower Defense Simulator", "genre": "Strategy", "upvotes": 2900,
     "description": "Place towers and defend against waves of enemies.", "devices": ["PC"], "tags": ["strategy", "co-op"]},
    {"game_id": "g5", "name": "Arsenal",              "genre": "FPS",       "upvotes": 2600,
     "description": "Fast-paced gun game with rotating weapons.", "devices": ["PC"], "tags": ["shooter", "competitive"]},
])

# NOTE: GameDatabase builds SBERT embeddings for 'description' — requires
# sentence-transformers (already in requirements.txt). First run downloads MiniLM.
db = GameDatabase(synthetic_catalog)
print(f"Loaded {len(db.df)} games; genres = {db._genres}")
"""
))

# 6. Instantiate the pipeline
cells.append(code(
"""# MatchaPipeline builds its LLM clients from cfg['llms'] using make_llm().
# Make sure the relevant API keys are exported before this cell.
pipeline = MatchaPipeline(cfg, db)
print("Pipeline ready. Agents:")
for name in ["llm_main", "llm_rank_a", "llm_rank_b", "llm_safety", "llm_explain"]:
    print(f"  {name}: {getattr(pipeline, name, None)}")
"""
))

# 7. Run a single recommendation
cells.append(code(
"""# One end-to-end turn. Risk control runs automatically on the input (and,
# if cfg['matcha']['risk_control']['check_output'] is true, on the output too).
query = "I love social games like Adopt Me and want something chill to play with friends on mobile."

result = pipeline.recommend(query, k=5)

print("Recommended game IDs:", result.game_ids)
print("Raw titles:", result.raw_titles)
print("\\nExplanations:")
for gid, exp in result.explanations.items():
    print(f"  - {gid}: {exp}")
"""
))

# 8. Inspect the output model
cells.append(code(
"""# RecOutput is a Pydantic model — every field is introspectable.
from schemas import RecOutput
print(RecOutput.model_fields.keys())
print("\\nFull result model dump:")
print(result.model_dump())
"""
))

# 9. Batch + full benchmark
cells.append(md(
"""## Running the full benchmark / ablations

The CLI in `main.py` reproduces the paper's experiments. Run from the repo root:

```bash
# Main table (Hit@5, Pop50, Factual, JP, Explanation Score)
python main.py --config config.yaml --experiment main --system matcha --limit 20

# Jailbreak robustness (WildJailbreak / DAN)
python main.py --config config.yaml --experiment jailbreak

# Ablations (risk control / ranking / reflection / candidate generation modules)
python main.py --config config.yaml --experiment ablation

# Explanation-quality judging
python main.py --config config.yaml --experiment judge
```

Add `--limit N` to cap the number of requests for a quick smoke run.
"""
))

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "cells": cells,
}

with open("walkthrough.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("wrote walkthrough.ipynb with", len(cells), "cells")
